# Práctica Clase 3

## Numpy

In [3]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [6]:
#Se pueden hacer muchas operaciones, las operaciones mas comunes son indexacion, iteracion, suma entre otros, aqui un ejemplo:
#Lista de python
lista_python = [1, 2, 3, 4, 5]

#Arreglo de NumPy
arreglo_numpy = np.array([1, 2, 3, 4, 5])

#Indexacion
primer_elemento_lista = lista_python[0]
primer_elemento_numpy = arreglo_numpy[0]

#Suma de elementos
suma_lista = sum(lista_python)
suma_numpy = np.sum(arreglo_numpy)

# Selección de subconjuntos
subconjunto_lista = lista_python[1:4]
subconjunto_numpy = arreglo_numpy[1:4]

print("\n\nResultados:")
print("Primer elemento en la lista:", primer_elemento_lista)
print("Primer elemento en el arreglo de NumPy:", primer_elemento_numpy)
print("Suma de la lista:", suma_lista)
print("Suma del arreglo de NumPy:", suma_numpy)
print("Subconjunto de la lista:", subconjunto_lista)
print("Subconjunto del arreglo de NumPy:", subconjunto_numpy)



Resultados:
Primer elemento en la lista: 1
Primer elemento en el arreglo de NumPy: 1
Suma de la lista: 15
Suma del arreglo de NumPy: 15
Subconjunto de la lista: [2, 3, 4]
Subconjunto del arreglo de NumPy: [2 3 4]


In [8]:
#Estas operaciones son numericas y multiplicacion de matrices, operaciones vectorizadas, funciones matematicas avanzadas, algebra lineal

lista_python = [1, 2, 3, 4, 5]
arreglo_numpy = np.array([1, 2, 3, 4, 5])

#Operaciones en un arreglo de umpy pero no en una lista
#Operaciones vectorizadas
arreglo_doble = arreglo_numpy * 2

# Broadcasting
arreglo_suma_constante = arreglo_numpy + 10

#Funciones matematicas
arreglo_cuadrado = np.square(arreglo_numpy)

#Algebra lineal(producto punto)
producto_punto = np.dot(arreglo_numpy, arreglo_numpy)

print("Operaciones en un arreglo de NumPy:")
print("Doble del arreglo:", arreglo_doble)
print("Suma de 10 a cada elemento:", arreglo_suma_constante)
print("Cuadrado de cada elemento:", arreglo_cuadrado)
print("Producto punto:", producto_punto)




Operaciones en un arreglo de NumPy:
Doble del arreglo: [ 2  4  6  8 10]
Suma de 10 a cada elemento: [11 12 13 14 15]
Cuadrado de cada elemento: [ 1  4  9 16 25]
Producto punto: 55


A partir de una lista podemos crear un arreglo de numpy

In [9]:
#La diferencia entre las formas (n,), (n,1) y (1,n) en NumPy radica en la dimensionalidad de los arreglos resultantes.
#Aunque todos representan arreglos unidimensionales, la forma específica puede afectar la forma en que NumPy trata los arreglos y cómo se realizan ciertas operaciones.

# Crear arreglos para cada forma
arreglo_n = np.array([1, 2, 3, 4, 5])

# Forma (n,)
arreglo_n_una_dimension = arreglo_n.reshape((5,))

# Forma (n,1)
arreglo_n_una_dimension_columna = arreglo_n.reshape((5, 1))

# Forma (1,n)
arreglo_n_una_dimension_fila = arreglo_n.reshape((1, 5))

# Imprimir arreglos
print("Arreglo original:")
print(arreglo_n)
print("\nForma (n,):")
print(arreglo_n_una_dimension)
print("\nForma (n,1):")
print(arreglo_n_una_dimension_columna)
print("\nForma (1,n):")
print(arreglo_n_una_dimension_fila)

Arreglo original:
[1 2 3 4 5]

Forma (n,):
[1 2 3 4 5]

Forma (n,1):
[[1]
 [2]
 [3]
 [4]
 [5]]

Forma (1,n):
[[1 2 3 4 5]]


In [2]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [3]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [12]:
lista + 1

NameError: name 'lista' is not defined

In [13]:
arreglo = arreglo + 1

NameError: name 'arreglo' is not defined

In [14]:
arreglo

NameError: name 'arreglo' is not defined

2. Elevar al cuadrado todos los elementos

In [8]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [9]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

3. Sumar todos los elementos

In [10]:
print(arreglo.sum())
print(lista.sum())

36


AttributeError: 'list' object has no attribute 'sum'

In [11]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [12]:
arreglo.shape

(6,)

In [28]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [30]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [31]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [25]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [ ]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

In [43]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [44]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [45]:
a3 = a1 * a2
a3.shape

(2, 4)

In [46]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [15]:
# Crear un arreglo con números enteros del 0 al 9
arreglo_enteros = np.arange(10)

# Imprimir el arreglo
print(arreglo_enteros)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# Crear un arreglo con 100 números equiespaciados del 0 al 9
arreglo_equiespaciado = np.linspace(0, 9, 100)

# Imprimir el arreglo
print(arreglo_equiespaciado)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [17]:
# Crear un arreglo con números enteros del 10 al 100
arreglo_enteros = np.arange(10, 101)

# Crear una máscara booleana para seleccionar los elementos divisibles por 3
mascara_divisibles_por_3 = (arreglo_enteros % 3 == 0)

# Seleccionar los elementos que cumplen con la condición
arreglo_divisibles_por_3 = arreglo_enteros[mascara_divisibles_por_3]

# Imprimir el arreglo original y el resultado
print("Arreglo original:")
print(arreglo_enteros)

print("\nElementos divisibles por 3:")
print(arreglo_divisibles_por_3)

Arreglo original:
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]

Elementos divisibles por 3:
[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]


**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [18]:
# Crear un arreglo de ceros de shape (5, 10)
arreglo_ceros = np.zeros((5, 10))

# Reemplazar la segunda y cuarta fila con unos
arreglo_ceros[1, :] = 1
arreglo_ceros[3, :] = 1

# Reemplazar la tercera y octava columna con dos
arreglo_ceros[:, 2] = 2
arreglo_ceros[:, 7] = 2

# Imprimir el arreglo resultante
print(arreglo_ceros)

[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [17]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[137.12277219, 187.22289567, 153.95764007],
        [175.21869487, 188.10311988, 118.02508687]],

       [[157.58773537, 166.74585121, 134.96866874],
        [128.3807111 , 188.91447629, 150.68622952]],

       [[168.77296873, 117.90287547, 115.19825164],
        [123.86197814, 172.33144425, 165.7329653 ]],

       [[157.35784374, 121.82035838, 100.01848734],
        [195.39977874, 188.95736542, 121.54200787]]])

In [18]:
a = np.random.random((4,4))

In [19]:
a

array([[0.48673571, 0.50465005, 0.33227167, 0.86611167],
       [0.14502147, 0.13692842, 0.56804006, 0.89177045],
       [0.78692331, 0.25942502, 0.88516122, 0.32876297],
       [0.78919257, 0.64347772, 0.02402004, 0.66363368]])

In [20]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [115]:
a

array([[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int16)

In [21]:
a.sum()

519

In [22]:
a.std()

23.924904214367643

In [23]:
a.sort(axis=1)

In [24]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [25]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [26]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [27]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [28]:
a = np.array([l])

In [31]:
a.shape

(1, 4, 6)

In [32]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [33]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [34]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [35]:
c = a * b 
print(c) 

[[91]]


In [11]:
d = b * a 
print(d)

NameError: name 'b' is not defined